[package]
name = "render-viewer"
version = "0.1.0"
authors = ["Fedor Rusak <fedor.rusak@infobip.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
fltk = "0.15.11"